# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OH20f9VubXAAfM82b8ULvHT4vMgt9KL8
"""

n = int(input("Input : "))
for i in range (n):
    for j in range (n):
        print ("*", end = "")
    print()

username = "Elinca Savina"
password = "121140073"

for i in range(3):

    input_username = input("Username anda : ")
    input_password = input("Password anda : ")
    if input_username == username and input_password == password:
        print("Berhasil Login!")
        break
    else:
        print("Username atau password salah coba lagi")
else:
    print("Akun Anda Diblokir")