# -*- coding: utf-8 -*-
"""121140073_Elinca Savina_Tugas2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OH20f9VubXAAfM82b8ULvHT4vMgt9KL8
"""

class Mahasiswa:
    def _init_(self, nama, nim, kelas_pbo_siakad, jumlah_sks):
        self.nama = nama
        self.nim = nim
        self.kelas_pbo_siakad = kelas_pbo_siakad
        self.jumlah_sks = jumlah_sks
    def memanggil_sks(self):
       print("jumlah sks", self.nama, "dengan nim", self.nim, "dari kelas pbo", self.kelas_pbo_siakad, "adalah", self.jumlah_sks)
mahasiswa1 = Mahasiswa("Elinca Savina", "121140073", "Rc", "23")
mahasiswa1.memanggil_sks()